// ─────────────────────────────────────────────────────────────────────────────
// Your Script, SEO source of truth
//
// One file drives the public SEO surface: page metadata, canonical URLs,
// structured data eligibility, the sitemap, llms.txt, robots.txt crawler policy,
// internal linking, and the validation tests. Edit content here; everything
// downstream is generated by `seo/generate.mjs` (run automatically before
// `vite build`). This keeps metadata, sitemap, llms.txt, JSON-LD, and tests
// from drifting apart.
//
// Honesty rules baked in (do not break):
//  • Describe only real product behavior (upload a script → choose a role →
//    practice lines cue-to-cue, solo). No invented features, pricing, reviews,
//    ratings, user counts, AI claims, integrations, or competitor facts.
//  • Structured data must match visible page content. FAQPage is emitted only
//    for pages whose FAQ items are rendered visibly (they are).
//  • No hidden text / cloaking / crawler-only content anywhere.
// ─────────────────────────────────────────────────────────────────────────────

export const SITE = {
  name: "Your Script",
  // Canonical base, used for every canonical, OG, Twitter, sitemap, JSON-LD,
  // and llms.txt URL. No trailing slash here; helpers add paths.
  urlBase: "https://www.yourscript.app",
  tagline: "A minimalist line rehearsal companion for actors and theatre students.",
  // Default / fallback OG image (a real file at public/og/home.png).
  ogImage: "/og/home.png",
  logo: "/brand/logo-mark.png",
  locale: "en_US",
  lang: "en",
  // Contact + social (real, owner-provided). Surfaced in Organization schema.
  // The "say hi" feedback form (/feedback?kind=say-hi) routes here.
  email: "impact@yourscript.app",
  sameAs: ["https://www.tiktok.com/@yourscriptapp"],
};

// ── Crawler policy ───────────────────────────────────────────────────────────
// Search / answer-engine bots (retrieval + citation) are allowed on public
// pages. Training / data-ingestion bots are disallowed by DEFAULT. These two
// flags are the only knobs the site owner usually needs. Flip to taste.
// RECOMMENDED POLICY (verified against OpenAI's and Anthropic's published bot
// docs): allow the search / answer / user-retrieval crawlers. That is how Your
// Script gets found and CITED in ChatGPT search, Claude, Perplexity, Google
// Search, and AI Overviews, and block the pure model-TRAINING crawlers by
// default. Blocking training has NO effect on being surfaced or cited by those
// answer engines (they use the allowed bots below), so this is the best default:
// stay maximally discoverable without donating the content to model training.
// To opt back into training later, move a name from trainingDisallowed → searchAllowed.
export const CRAWLERS = {
  searchAllowed: [
    "Googlebot", // Google Search + AI Overviews
    "Bingbot", // Bing + Copilot
    "OAI-SearchBot", // ChatGPT search indexing / citation
    "ChatGPT-User", // live fetch when a ChatGPT user asks
    "Claude-SearchBot", // Claude search indexing
    "Claude-User", // live fetch when a Claude user asks
    "PerplexityBot", // Perplexity answer engine
  ],
  trainingDisallowed: [
    "GPTBot", // OpenAI model training
    "ClaudeBot", // Anthropic model training
    "Google-Extended", // Gemini/Vertex training (NOT a Google Search ranking signal)
  ],
};

// ── Private routes ───────────────────────────────────────────────────────────
// The real app/account surface. These must NEVER appear in the sitemap or
// llms.txt, are disallowed in robots.txt, AND are noindex'd client-side (the
// inline script in index.html). robots.txt alone is not a privacy mechanism.
export const PRIVATE_ROUTES = [
  "/upload", // the app itself
  "/dashboard", // user dashboard
  "/feedback", // utility form, not SEO content
  // Defensive: not currently routed, but reserved so future auth/account
  // surfaces are excluded by default.
  "/account",
  "/admin",
  "/auth",
  "/login",
  "/signup",
  "/settings",
];

// robots.txt Disallow lines (paths/prefixes). Trailing slash = prefix only.
export const PRIVATE_DISALLOW = [
  "/upload",
  "/dashboard",
  "/feedback",
  "/account/",
  "/admin/",
  "/auth/",
  "/login",
  "/signup",
  "/settings/",
  "/api/",
];

// ── Helpers ──────────────────────────────────────────────────────────────────
export function canonicalFor(path) {
  if (path === "/") return SITE.urlBase + "/";
  return SITE.urlBase + path;
}
export function absUrl(p) {
  return p.startsWith("http") ? p : SITE.urlBase + p;
}

// ── Pages ────────────────────────────────────────────────────────────────────
// `generate: false` → not a generated static file (the homepage is the SPA in
// index.html), but still listed in sitemap/llms. `body` holds the visible
// sections only. The generator adds the <h1>, the FAQ accordion (rendered from
// `faqs`, guaranteeing schema/visible parity), the CTA, and the footer nav.

export const PAGES = [
  // ── Homepage (SPA, metadata lives in index.html; listed here for sitemap/llms) ──
  {
    slug: "home",
    path: "/",
    generate: false,
    inSitemap: true,
    inLlms: true,
    llmsSection: "Core",
    llmsTitle: "Homepage",
    llmsDesc: "Product homepage for Your Script.",
    title: "Your Script | Minimal Line Rehearsal Companion",
    description:
      "Your Script helps actors and theatre students upload scripts, choose roles, and rehearse cue to cue without a scene partner.",
    type: "home",
    intent: "Product / entity (brand, what is yourscript.app)",
    primaryQueries: ["your script app", "yourscript.app", "line rehearsal companion"],
    secondaryQueries: ["app for actors to memorize lines"],
    schema: ["WebSite", "Organization", "SoftwareApplication"],
  },

  // ── /what-is-yourscript (entity / about) ──
  {
    slug: "what-is-yourscript",
    path: "/what-is-yourscript",
    file: "what-is-yourscript.html",
    generate: true,
    inSitemap: true,
    inLlms: true,
    llmsSection: "Core",
    llmsTitle: "What Is Your Script?",
    llmsDesc:
      "Clear explanation of what Your Script does, who uses the app, what problem the app solves, and how rehearsal works.",
    title: "What Is Your Script? | Line Rehearsal Companion",
    description:
      "Learn what Your Script does, who uses the app, and how cue based solo rehearsal works for actors and theatre students.",
    h1: "What Is Your Script?",
    type: "about",
    intent: "Product / entity definition",
    primaryQueries: ["what is your script", "your script app"],
    secondaryQueries: ["line rehearsal companion", "yourscript.app"],
    internalLinksOut: [
      "/memorize-lines",
      "/how-to-memorize-a-script",
      "/rehearse-without-a-scene-partner",
      "/compare/line-learning-apps",
    ],
    schema: ["AboutPage", "SoftwareApplication", "FAQPage"],
    cta:
      "Open Your Script, upload a scene, and run your lines from cues.",
    faqs: [
      {
        q: "What is Your Script?",
        a: "Your Script is a line rehearsal web app for actors and theatre students. You upload a script, choose your role, and practice each line from its cue. The app keeps the work focused on recall.",
      },
      {
        q: "Who is Your Script for?",
        a: "Your Script helps actors getting off-book, theatre students working on scenes, and musical theatre performers rehearsing dialogue between songs. The app fits auditions, class scenes, and productions.",
      },
      {
        q: "Do I need a scene partner to use Your Script?",
        a: "No. Your Script treats the other characters' lines as your cues. You see the cue, then deliver your line from memory. Use the app when a scene partner is not available or when you need a quick run before rehearsal.",
      },
      {
        q: "Do I need to download anything?",
        a: "No. Your Script runs in your web browser, so there is nothing to download or install. Open it on a laptop, tablet, or phone, upload a script, choose your role, and start running lines. It works the same way across your devices.",
      },
    ],
    body: `
<section class="quick-answer" data-rough data-rough-double data-rough-seed="2" aria-labelledby="quick-answer">
  <h2 id="quick-answer">Quick answer</h2>
  <p>Your Script helps actors and theatre students run lines alone. Upload a script, choose your role, and practice each line from its cue. The app keeps rehearsal focused on recall, timing, and missed lines.</p>
</section>

<section aria-labelledby="what-it-is">
  <h2 id="what-it-is">What Your Script is</h2>
  <p>Your Script turns a script into cue and line pairs. The line before yours becomes the cue. Your line becomes the answer you practice from memory. You work through the scene one cue at a time.</p>
</section>

<section aria-labelledby="who-its-for">
  <h2 id="who-its-for">Who uses Your Script</h2>
  <ul>
    <li>Actors getting off-book for a play or a production.</li>
    <li>Theatre students rehearsing class scenes and monologues.</li>
    <li>Musical theatre performers running dialogue between numbers.</li>
    <li>Anyone preparing audition sides on a short timeline.</li>
  </ul>
</section>

<section aria-labelledby="problem">
  <h2 id="problem">What problem Your Script solves</h2>
  <p>Rereading feels useful, but recall starts when you hear a cue and answer without looking. Solo practice often means recordings, a covered page, or another person. Your Script holds the cues so you work on recall.</p>
</section>

<section aria-labelledby="how-it-works">
  <h2 id="how-it-works">How Your Script works</h2>
  <ol>
    <li><strong>Upload your script.</strong> Your Script reads it into characters and dialogue.</li>
    <li><strong>Choose your role.</strong> Choose the character you are playing.</li>
    <li><strong>Practice cue-to-cue.</strong> See the cue, deliver your line, then run missed lines again right away.</li>
  </ol>
</section>

<section aria-labelledby="use-cases">
  <h2 id="use-cases">Common use cases</h2>
  <ul>
    <li>Getting off-book before blocking rehearsals begin.</li>
    <li>Drilling audition sides the night before.</li>
    <li>Working a single tricky scene until the cues feel automatic.</li>
    <li>Refreshing lines you have not touched in a week.</li>
  </ul>
</section>

<section aria-labelledby="different">
  <h2 id="different">What makes Your Script different</h2>
  <p>Your Script does one job: cue based solo rehearsal. No feeds. No production dashboard. Upload a script, pick a role, and start.</p>
</section>

<section aria-labelledby="what-it-isnt">
  <h2 id="what-it-isnt">What Your Script is not</h2>
  <p>Your Script is not a teleprompter, casting tool, classroom system, acting coach, or full script platform. The app supports one rehearsal step: learning lines. The creative work stays yours.</p>
</section>

<section aria-labelledby="key-terms">
  <h2 id="key-terms">Key terms</h2>
  <dl>
    <dt>Cue</dt>
    <dd>The line, usually another character's, that comes right before yours and signals your turn to speak.</dd>
    <dt>Cue-to-cue rehearsal</dt>
    <dd>Practising your lines as answers to the cues that trigger them, so the hand-off between lines becomes automatic.</dd>
    <dt>Off-book</dt>
    <dd>Able to perform without holding the script, recalling your lines from memory.</dd>
    <dt>Sides</dt>
    <dd>The short excerpt of a script used for an audition, rather than the whole play.</dd>
  </dl>
</section>
`,
  },

  // ── /memorize-lines (fast, practical) ──
  {
    slug: "memorize-lines",
    path: "/memorize-lines",
    file: "memorize-lines.html",
    generate: true,
    inSitemap: true,
    inLlms: true,
    llmsSection: "Guides",
    llmsTitle: "Memorize Lines Faster",
    llmsDesc:
      "Practical guide to memorizing lines faster, practicing cues, and getting off-book.",
    title: "Memorize Lines Faster | Your Script",
    description:
      "Learn practical ways to memorize lines faster, rehearse cue to cue, and get off-book with a clean actor workflow.",
    h1: "Memorize Lines Faster",
    type: "guide",
    intent: "Line memorization (how to memorize lines fast / get off-book)",
    primaryQueries: ["memorize lines", "memorize lines faster", "how to memorize lines fast"],
    secondaryQueries: ["how do actors memorize lines", "get off book", "cue to cue rehearsal"],
    internalLinksOut: [
      "/how-to-memorize-a-script",
      "/rehearse-without-a-scene-partner",
      "/compare/line-learning-apps",
      "/what-is-yourscript",
    ],
    schema: ["WebPage", "FAQPage"],
    cta:
      "Open Your Script and drill a scene cue to cue.",
    faqs: [
      {
        q: "How do actors memorize lines faster?",
        a: "They understand the scene before drilling, break the scene into small chunks, and recall each line from its cue. Speed comes from active recall under light pressure. Test yourself, then rerun missed lines right away.",
      },
      {
        q: "What is cue-based rehearsal?",
        a: "Cue based rehearsal means practicing your line as a response to the line before yours. That cue triggers your next line. This matches how scenes run in rehearsal and performance.",
      },
      {
        q: "Should I memorize the cue lines too?",
        a: "Yes, at least enough to recognize them. You do not need the other character's lines word perfect. You need to know what triggers yours. Cues prevent long pauses when you remember the line but miss the entrance.",
      },
      {
        q: "How long to memorize lines?",
        a: "Time depends on length, language, and practice frequency. Short sessions over several days beat one long cram. Spaced recall with cues usually holds better than marathon repetition.",
      },
    ],
    body: `
<section class="quick-answer" data-rough data-rough-double data-rough-seed="2" aria-labelledby="quick-answer">
  <h2 id="quick-answer">Quick answer</h2>
  <p>To memorize lines faster, understand the scene first. Break the scene into small chunks. Drill cue to cue with short active recall loops. Run missed lines again right away. Keep sessions short and frequent.</p>
</section>

<section aria-labelledby="understand">
  <h2 id="understand">Start with understanding, not repetition</h2>
  <p>Before you drill a line, know what the scene does and what your character wants. Lines with meaning are easier to recall than strings of words. Read for beats, turns, and the reason each line follows the one before.</p>
</section>

<section aria-labelledby="chunk">
  <h2 id="chunk">Break scenes into smaller sections</h2>
  <p>Do not learn a whole scene in one pass. Split the scene into short beats. Get one beat solid before adding the next. This shows you where the weak lines are.</p>
</section>

<section aria-labelledby="cue">
  <h2 id="cue">Practice cue-to-cue</h2>
  <p>Memorize the handoff, not only your words. Learn the lines right before yours. Each cue should trigger your next line. Cue to cue practice matches performance pressure better than reading your lines in order.</p>
</section>

<section aria-labelledby="recall">
  <h2 id="recall">Use short recall loops</h2>
  <p>Active recall beats rereading. Cover your lines, take the cue, deliver from memory, then check. When you miss a line, run the line again right away. Short loops across several days work better than one long session.</p>
</section>

<section aria-labelledby="where">
  <h2 id="where">Where Your Script helps</h2>
  <p>Your Script turns a scene into cue and line pairs. You run recall loops alone without recording every part or covering the page by hand. See the cue, say your line, and keep moving.</p>
</section>
`,
  },

  // ── /how-to-memorize-a-script (broad, step-by-step) ──
  {
    slug: "how-to-memorize-a-script",
    path: "/how-to-memorize-a-script",
    file: "how-to-memorize-a-script.html",
    generate: true,
    inSitemap: true,
    inLlms: true,
    llmsSection: "Guides",
    llmsTitle: "How to Memorize a Script",
    llmsDesc:
      "Step-by-step guide to memorizing scripts, scenes, class material, and audition sides.",
    title: "How to Memorize a Script | Your Script Guide",
    description:
      "A clear guide to memorizing a script for auditions, class, theatre, and musical theatre without clutter, gimmicks, or spammy rehearsal hacks.",
    h1: "How to Memorize a Script",
    type: "guide",
    intent: "Script memorization guide (full script / scene / sides)",
    primaryQueries: ["how to memorize a script", "memorize a play script", "script memorization"],
    secondaryQueries: [
      "how to memorize a theatre script",
      "how actors memorize scripts",
      "memorize a script for an audition",
    ],
    internalLinksOut: [
      "/memorize-lines",
      "/rehearse-without-a-scene-partner",
      "/what-is-yourscript",
      "/compare/line-learning-apps",
    ],
    schema: ["WebPage", "FAQPage"],
    cta:
      "When you are ready to run cue to cue, open Your Script and rehearse the scene on your own.",
    faqs: [
      {
        q: "How long to memorize a script?",
        a: "Time depends on length, density, and practice frequency. A short scene might take a few focused sessions. A lead role takes weeks. Use short recall practice across several days instead of one cram session.",
      },
      {
        q: "How do you memorize a script for an audition?",
        a: "Focus on the sides you were given. Read for intention, break the scene into a few beats, and drill cue to cue until the handoffs feel steady. Leave room to look up, listen, and take direction.",
      },
      {
        q: "How is memorizing a musical different?",
        a: "A musical asks you to hold dialogue, lyrics, blocking, and timing at once. Treat spoken scenes and songs as separate jobs. Then rehearse the handoffs between dialogue and music.",
      },
      {
        q: "What is the fastest way to get off-book?",
        a: "Practice recall instead of rereading. Cover your lines, take each cue, and deliver from memory. Rerun misses right away. Keep sessions short and frequent across several days.",
      },
    ],
    body: `
<section class="quick-answer" data-rough data-rough-double data-rough-seed="2" aria-labelledby="quick-answer">
  <h2 id="quick-answer">Quick answer</h2>
  <p>To memorize a script, read for meaning and beats. Break the script into manageable sections. Rehearse cue by cue. Practice recall away from the page in short sessions over several days.</p>
</section>

<section aria-labelledby="beats">
  <h2 id="beats">Read for beats and intention</h2>
  <p>Start with the story, your character's arc, and the job of each scene. Mark the beats where the scene shifts. Note why each line follows the one before. Meaning gives memory a stronger path than word order alone.</p>
</section>

<section aria-labelledby="chunk">
  <h2 id="chunk">Chunk the script into workable sections</h2>
  <p>Do not learn the script end to end in one pass. Break the script into scenes, then into short beats of a few exchanges. Get one chunk solid before adding the next. This keeps progress visible and weak spots obvious.</p>
</section>

<section aria-labelledby="cue">
  <h2 id="cue">Rehearse cue-by-cue</h2>
  <p>Learn your lines as responses to cues. Know the line right before yours well enough to recognize the entrance. Cue by cue rehearsal helps lines hold under pressure.</p>
</section>

<section aria-labelledby="recall">
  <h2 id="recall">Practice recall without staring at the page</h2>
  <p>Once a chunk feels familiar, put the script down. Take the cue and deliver from memory. Then check yourself. Run missed lines again right away. Retrieval moves a scene from recognition to recall.</p>
</section>

<section aria-labelledby="digital">
  <h2 id="digital">Use digital repetition without clutter</h2>
  <p>A tool should hold your cues and stay out of the way. The work is repetition and recall, not settings. Your Script lets you upload the script, pick your role, and rehearse cue to cue, including dialogue between songs in a musical.</p>
</section>
`,
  },

  // ── /rehearse-without-a-scene-partner (solo) ──
  {
    slug: "rehearse-without-a-scene-partner",
    path: "/rehearse-without-a-scene-partner",
    file: "rehearse-without-a-scene-partner.html",
    generate: true,
    inSitemap: true,
    inLlms: true,
    llmsSection: "Guides",
    llmsTitle: "Rehearse Without a Scene Partner",
    llmsDesc:
      "Guide to solo rehearsal, cue-based practice, and running lines alone.",
    title: "Rehearse Without a Scene Partner | Your Script",
    description:
      "Practice scenes on your own with a rehearsal workflow that helps actors and students stay on cues, build confidence, and prepare faster.",
    h1: "Rehearse Without a Scene Partner",
    type: "guide",
    intent: "Solo rehearsal (run lines alone / no scene partner)",
    primaryQueries: [
      "rehearse without a scene partner",
      "run lines alone",
      "practice lines by myself",
    ],
    secondaryQueries: ["practice scenes alone", "scene partner app", "how to run lines by yourself"],
    internalLinksOut: [
      "/memorize-lines",
      "/how-to-memorize-a-script",
      "/compare/line-learning-apps",
      "/what-is-yourscript",
    ],
    schema: ["WebPage", "FAQPage"],
    cta:
      "No partner around? Open Your Script and run the scene from cues.",
    faqs: [
      {
        q: "How do I rehearse without a scene partner?",
        a: "Treat the other characters' lines as cues. Read or play the cue, then deliver your line from memory. Focus on recall and timing instead of reading both parts aloud.",
      },
      {
        q: "How do I run lines by myself?",
        a: "Cover your own lines and reveal them to check. Take each cue, say your line from memory, and rerun anything you miss before moving on. Keep the loop tight and get the script out of your hands early.",
      },
      {
        q: "What is a cue line?",
        a: "A cue line is the line spoken right before yours. The cue tells you when to speak. In solo rehearsal, reliable cue recognition keeps timing tight. You do not need other parts word perfect. You need the entrances.",
      },
      {
        q: "Is solo rehearsal as good as rehearsing with a partner?",
        a: "They do different jobs. Solo rehearsal helps you learn lines, cues, and timing on your own schedule. Partner rehearsal adds listening, staging, and shared choices. Use solo work to get off-book before the room work starts.",
      },
    ],
    body: `
<section class="quick-answer" data-rough data-rough-double data-rough-seed="2" aria-labelledby="quick-answer">
  <h2 id="quick-answer">Quick answer</h2>
  <p>Rehearse without a scene partner by treating the other characters' lines as cues. Take the cue, then deliver your line from memory. Practice recall and timing instead of reading both parts aloud.</p>
</section>

<section aria-labelledby="why-hard">
  <h2 id="why-hard">Why solo rehearsal is hard</h2>
  <p>On your own, rereading the page feels productive. Recall needs a cue, a response, and a check. Without cues or timing pressure, a scene often falls apart when another actor speaks.</p>
</section>

<section aria-labelledby="workarounds">
  <h2 id="workarounds">Common workarounds</h2>
  <ul>
    <li>Recording the other parts and playing them back to cue yourself.</li>
    <li>Covering your lines with a hand or a card and revealing to check.</li>
    <li>Asking a friend or family member to read in.</li>
    <li>Using an app that holds the cues for you.</li>
  </ul>
  <p>Each method works. The difference is setup time before rehearsal starts.</p>
</section>

<section aria-labelledby="cue-helps">
  <h2 id="cue-helps">How cue-based rehearsal helps</h2>
  <p>Cue based rehearsal keeps the focus on the handoff. You get the cue, recall your line, and rerun anything you miss. You practice the trigger and response the scene uses in the room.</p>
</section>

<section aria-labelledby="when">
  <h2 id="when">When to use Your Script</h2>
  <p>Use Your Script when you have a scene to learn and no one to run lines with. Upload the script, choose your role, and turn the other lines into cues. Get off-book first, then use partner rehearsals for acting work.</p>
</section>
`,
  },

  // ── /compare/line-learning-apps (neutral comparison) ──
  {
    slug: "compare-line-learning-apps",
    path: "/compare/line-learning-apps",
    file: "compare/line-learning-apps.html",
    generate: true,
    inSitemap: true,
    inLlms: true,
    llmsSection: "Comparison",
    llmsTitle: "Compare Line Learning Apps",
    llmsDesc:
      "Neutral guide to choosing a line-learning or rehearsal app based on workflow.",
    title: "Line Learning App Comparison | Your Script Guide",
    description:
      "Compare line-learning and rehearsal app workflows for actors, theatre students, teachers, and musical theatre performers, including solo rehearsal and cue-based practice.",
    h1: "Compare Line Learning Apps",
    type: "comparison",
    intent: "App / comparison (choosing a line-learning or rehearsal app)",
    primaryQueries: [
      "line learning app",
      "best app to memorize lines",
      "script memorization app",
    ],
    secondaryQueries: ["rehearsal app for actors", "app for actors to memorize lines"],
    internalLinksOut: [
      "/what-is-yourscript",
      "/rehearse-without-a-scene-partner",
      "/memorize-lines",
      "/how-to-memorize-a-script",
    ],
    schema: ["WebPage", "FAQPage"],
    cta:
      "If a minimal cue based workflow fits your rehearsal, open Your Script and try a scene.",
    faqs: [
      {
        q: "What should I look for in a line-learning app?",
        a: "Match the app to your rehearsal habits. Look at audio playback, repetition tools, cue practice, solo use, setup time, and script support. The best tool gets you practicing quickly.",
      },
      {
        q: "Is there a single best app to memorize lines?",
        a: "No single app fits every actor. Some actors prefer recording and playback. Some want flashcard style repetition. Others want cue based solo rehearsal. Pick for your habits, not for a label.",
      },
      {
        q: "How is Your Script different from other line-learning apps?",
        a: "Your Script focuses on minimal cue based solo rehearsal. Upload a script, pick your role, and run your lines from cues. The app leaves out production management and social features.",
      },
    ],
    body: `
<section class="quick-answer" data-rough data-rough-double data-rough-seed="2" aria-labelledby="quick-answer">
  <h2 id="quick-answer">Quick answer</h2>
  <p>The best line-learning app depends on your rehearsal habits. Common workflows include recording and playback, cue triggered readers, teleprompters, and cue based solo recall. Your Script fits the last group. You run lines from cues without recording every part.</p>
</section>

<section aria-labelledby="criteria">
  <h2 id="criteria">What to look for in a line-learning app</h2>
  <ul>
    <li><strong>How you learn:</strong> audio playback, repetition, or cue and recall.</li>
    <li><strong>Solo vs. partner:</strong> whether you mostly rehearse alone.</li>
    <li><strong>Setup and clutter:</strong> how much work comes before practice.</li>
    <li><strong>Your material:</strong> whether the app works with the kind of script you use.</li>
    <li><strong>Focus:</strong> a single rehearsal tool versus a broader platform.</li>
  </ul>
</section>

<section aria-labelledby="apps">
  <h2 id="apps">A few well-known apps</h2>
  <p>Short, neutral notes on how each tool approaches rehearsal. Features and pricing change often. Check each app&#39;s own site or store listing for current details.</p>
  <h3 id="coldread">ColdRead</h3>
  <p>An iOS app built around a cue triggered reader. Speak the last word of your line and the app reads the next line back. The app also includes a teleprompter.</p>
  <h3 id="rehearsal-pro">Rehearsal Pro</h3>
  <p>An actor focused app with a teleprompter, line highlighting, blackout, adjustable pacing, repeat and playback, and beat marking.</p>
  <h3 id="linelearner">LineLearner</h3>
  <p>Built around recording. You record each character&#39;s lines or split them with castmates, then play them back to rehearse together. The app supports script import as text chunks.</p>
  <h3 id="script-rehearser">Script Rehearser</h3>
  <p>Lets you record your own lines or have synthetic voices read them back, after importing a script or typing your lines in.</p>
</section>

<section aria-labelledby="table">
  <h2 id="table">Comparison at a glance</h2>
  <div class="table-wrap" data-rough data-rough-seed="3">
    <table>
      <caption>A neutral summary of each tool&#39;s core approach. Features and platforms change. Verify on each app&#39;s site.</caption>
      <thead>
        <tr>
          <th scope="col">App</th>
          <th scope="col">Core approach</th>
          <th scope="col">Platform</th>
        </tr>
      </thead>
      <tbody>
        <tr><th scope="row">ColdRead</th><td>Cue-triggered reader + teleprompter</td><td>iOS</td></tr>
        <tr><th scope="row">Rehearsal Pro</th><td>Feature-rich teleprompter (highlight, blackout, pacing)</td><td>iOS</td></tr>
        <tr><th scope="row">LineLearner</th><td>Record parts and play them back; rehearse with castmates</td><td>iOS &middot; Android</td></tr>
        <tr><th scope="row">Script Rehearser</th><td>Record or synthetic-voice playback</td><td>iOS</td></tr>
        <tr><th scope="row">Your Script <span class="tag" data-rough="pill" data-rough-seed="7"><span>Cue-based &middot; solo</span></span></th><td>Run your lines from cues with minimal setup</td><td>Web (any device)</td></tr>
      </tbody>
    </table>
  </div>
</section>

<section aria-labelledby="fit-simple">
  <h2 id="fit-simple">Best fit for simplicity</h2>
  <p>If you want the shortest path from "I have a scene" to "I am rehearsing," look for a tool with little setup and few distractions. The less time you spend configuring, recording, or building decks, the more time goes to actual recall practice.</p>
</section>

<section aria-labelledby="fit-solo">
  <h2 id="fit-solo">Best fit for solo rehearsal</h2>
  <p>If you usually rehearse alone, prioritize a cue based workflow. Reading both parts aloud feels useful but does little for recall. Cue and response is closer to stage pressure. See <a href="/rehearse-without-a-scene-partner">rehearsing without a scene partner</a> for the method.</p>
</section>

<section aria-labelledby="fit-broad">
  <h2 id="fit-broad">Best fit for broader workflows</h2>
  <p>If you need full script management, scheduling, or collaboration, a broader platform might fit better. Expect more setup. Some actors use a broad tool for organization and a lighter tool for daily line work.</p>
</section>

<section aria-labelledby="where">
  <h2 id="where">Where Your Script fits</h2>
  <p>Your Script fits the minimal, cue based, solo end of the line learning app spectrum. Upload a script, choose your role, and run lines from cues. Choose another approach if you want recording, collaboration, or production tools.</p>
</section>
`,
  },

  // ── /audition-sides-practice (audition prep) ──
  {
    slug: "audition-sides-practice",
    path: "/audition-sides-practice",
    file: "audition-sides-practice.html",
    generate: true,
    inSitemap: true,
    inLlms: true,
    llmsSection: "Guides",
    llmsTitle: "Practice Audition Sides",
    llmsDesc: "How to learn and rehearse audition sides on a short timeline.",
    title: "How to Practice Audition Sides | Your Script",
    description:
      "Learn audition sides on a short timeline: focus on intention, stay flexible enough to take direction, and rehearse the sides on your own.",
    h1: "Practice Audition Sides",
    type: "guide",
    intent: "Audition sides preparation (learn and practice sides fast)",
    primaryQueries: ["practice audition sides", "how to memorize audition sides", "memorize sides fast"],
    secondaryQueries: ["audition preparation", "learn sides overnight", "cold read practice"],
    internalLinksOut: [
      "/memorize-lines",
      "/rehearse-without-a-scene-partner",
      "/cue-to-cue-rehearsal",
      "/what-is-yourscript",
    ],
    schema: ["WebPage", "FAQPage"],
    cta: "Got sides to learn? Open Your Script, drop them in, and run them from your cues.",
    faqs: [
      {
        q: "How do I memorize audition sides quickly?",
        a: "Read the sides for what the scene wants, then drill your lines from their cues in short, repeated passes. Aim to be off-book enough to look up and react, not perfectly word-locked. Re-run the lines you miss right away, and practice out loud.",
      },
      {
        q: "Should I be fully off-book for an audition?",
        a: "Usually you should be off-book enough to make eye contact and take direction, but you can still hold the sides. Casting often cares more about your choices and how you adjust than about flawless recall, so prioritize intention and flexibility over word-perfect memory.",
      },
      {
        q: "What are audition sides?",
        a: "Sides are the short excerpt of a script used for an audition, rather than the whole play. They are often only a page or two and may arrive a day, or even minutes, before you read, so a fast, focused way to learn them helps.",
      },
      {
        q: "Can I practice sides without a reader?",
        a: "Yes. Treat the other character's lines as your cues and answer from memory. Practicing the cues, not just your own lines, keeps your timing steady when a real reader feeds you the scene at the audition.",
      },
    ],
    body: `
<section class="quick-answer" data-rough data-rough-double data-rough-seed="2" aria-labelledby="quick-answer">
  <h2 id="quick-answer">Quick answer</h2>
  <p>To practice audition sides, learn them fast and stay flexible. Read for what the scene wants, drill your lines from their cues, and get off-book enough to look up and take direction. Word-perfect recall matters less than clear choices you can adjust on the spot.</p>
</section>

<section aria-labelledby="read-first">
  <h2 id="read-first">Read the sides for choices, not just words</h2>
  <p>An audition tests your choices and how you take direction. Before you drill, decide what your character wants in the scene and how the lines move toward it. Those choices give your memory something to hold and give the room something to respond to.</p>
</section>

<section aria-labelledby="flexible">
  <h2 id="flexible">Learn it well enough to look up</h2>
  <p>Being glued to the page hides your face; being robotically word-locked makes redirection hard. Aim for the middle: off-book enough to glance up, make eye contact, and shift if the casting director asks for something new.</p>
</section>

<section aria-labelledby="cues">
  <h2 id="cues">Drill the cues, not only your lines</h2>
  <p>At the audition a reader feeds you the other lines. If you have practiced your lines as answers to those cues, their timing will not throw you. Learn the cue that sets up each of your lines so the hand-off stays automatic.</p>
</section>

<section aria-labelledby="out-loud">
  <h2 id="out-loud">Practice out loud and on your feet</h2>
  <p>Say the lines aloud at performance volume, and stand if you will stand in the room. Recall under those conditions is what holds up, far more than silent rereading at your desk.</p>
</section>

<section aria-labelledby="where">
  <h2 id="where">Where Your Script helps</h2>
  <p>Drop your sides into Your Script, choose your role, and run them cue to cue on your own. It is built for exactly this: a short scene to learn quickly, with no reader on hand. For the broader method, see the guide on memorizing lines faster.</p>
</section>
`,
  },

  // ── /memorize-a-monologue (monologue work) ──
  {
    slug: "memorize-a-monologue",
    path: "/memorize-a-monologue",
    file: "memorize-a-monologue.html",
    generate: true,
    inSitemap: true,
    inLlms: true,
    llmsSection: "Guides",
    llmsTitle: "Memorize a Monologue",
    llmsDesc:
      "A method for memorizing a monologue: follow the argument, chunk by thought, and anchor the transitions.",
    title: "How to Memorize a Monologue | Your Script",
    description:
      "Memorize a monologue by following its argument, chunking by thought, and anchoring transitions, the method for a speech with no cues to lean on.",
    h1: "How to Memorize a Monologue",
    type: "guide",
    intent: "Monologue memorization (single speaker, no cues)",
    primaryQueries: ["how to memorize a monologue", "memorize a monologue fast", "monologue memorization"],
    secondaryQueries: ["learn a monologue", "memorize a speech for acting", "audition monologue"],
    internalLinksOut: [
      "/memorize-lines",
      "/how-to-memorize-a-script",
      "/audition-sides-practice",
      "/what-is-yourscript",
    ],
    schema: ["WebPage", "FAQPage"],
    cta: "Working a monologue? Open Your Script and rehearse it line by line.",
    faqs: [
      {
        q: "How is memorizing a monologue different from a scene?",
        a: "A monologue has no scene partner and no cues to trigger your next line, so you cannot lean on a hand-off. Instead you follow the speech's own logic, the way one thought leads to the next, which makes understanding the argument matter even more than in a scene.",
      },
      {
        q: "How long does it take to memorize a monologue?",
        a: "It depends on the length and density of the speech and how often you practice. Short, frequent recall sessions across several days lock a monologue in more reliably than one long cram, and a minute-long piece often comes together faster than expected with daily passes.",
      },
      {
        q: "How do I stop blanking in the middle of a monologue?",
        a: "Blanks usually happen at the seams between thoughts. Find each place the speech turns and rehearse those transitions on their own, so the end of one thought reliably triggers the start of the next. Practicing the joins, not just the lines, removes most mid-speech freezes.",
      },
      {
        q: "Can Your Script help with a monologue?",
        a: "Yes. Even without another character's cues, you can run a monologue line by line, revealing each line only to check and re-running the ones you miss. That keeps the work on active recall rather than rereading.",
      },
    ],
    body: `
<section class="quick-answer" data-rough data-rough-double data-rough-seed="2" aria-labelledby="quick-answer">
  <h2 id="quick-answer">Quick answer</h2>
  <p>A monologue has no scene partner and no cues, so your memory rides the speech's own logic. Follow the argument, chunk the speech by thought rather than by line, and rehearse the transitions where one thought becomes the next. Then practice recall in short, frequent passes.</p>
</section>

<section aria-labelledby="argument">
  <h2 id="argument">Follow the argument, not the words</h2>
  <p>A monologue is a single line of thought moving somewhere. Map that journey first: what the character wants, and how each idea pushes toward it. When you know why one thought follows another, the words become far easier to recall in order.</p>
</section>

<section aria-labelledby="chunk">
  <h2 id="chunk">Chunk by thought, not by line</h2>
  <p>Break the speech into beats of meaning rather than equal-sized blocks of text. Learn one beat solidly before adding the next. Beats give you natural handholds, so you always know which idea comes next even if a phrase slips.</p>
</section>

<section aria-labelledby="transitions">
  <h2 id="transitions">Anchor the transitions</h2>
  <p>Most blanks happen at the seams between thoughts, not inside them. Rehearse those joins on their own until the end of one beat reliably triggers the start of the next. The transitions are the load-bearing part of a monologue.</p>
</section>

<section aria-labelledby="recall">
  <h2 id="recall">Practice recall, in order and out of order</h2>
  <p>Once the speech is roughly learned, deliver it from memory and check only when stuck. Then test single beats out of order, so your recall does not depend on running from the top every time. That is what keeps a monologue steady under nerves.</p>
</section>

<section aria-labelledby="where">
  <h2 id="where">Where Your Script helps</h2>
  <p>Load your monologue into Your Script and run it line by line, revealing each line only to check and re-running the ones you miss. It keeps the work on recall, even when there are no cues to lean on.</p>
</section>
`,
  },

  // ── /cue-to-cue-rehearsal (definition + method; anchors the core mechanic) ──
  {
    slug: "cue-to-cue-rehearsal",
    path: "/cue-to-cue-rehearsal",
    file: "cue-to-cue-rehearsal.html",
    generate: true,
    inSitemap: true,
    inLlms: true,
    llmsSection: "Guides",
    llmsTitle: "Cue-to-Cue Rehearsal",
    llmsDesc: "What a cue line is, what cue-to-cue rehearsal means, and how to drill cues on your own.",
    title: "Cue-to-Cue Rehearsal: What It Is and How to Do It | Your Script",
    description:
      "What a cue line is, what cue-to-cue rehearsal means for actors, and how to drill your cues solo so your lines hold up in a run.",
    h1: "Cue-to-Cue Rehearsal",
    type: "guide",
    intent: "Definition and method for cue-to-cue rehearsal and cue lines",
    primaryQueries: ["cue to cue rehearsal", "what is a cue line", "cue to cue meaning"],
    secondaryQueries: ["rehearse cues", "cue line practice", "what does off book mean"],
    internalLinksOut: [
      "/rehearse-without-a-scene-partner",
      "/memorize-lines",
      "/how-to-memorize-a-script",
      "/what-is-yourscript",
    ],
    schema: ["WebPage", "FAQPage"],
    cta: "Want to drill your cues? Open Your Script and run the scene cue to cue.",
    faqs: [
      {
        q: "What is a cue line?",
        a: "A cue line is the line spoken right before yours, the trigger that tells you it is your turn. In rehearsal it is the most useful thing to know, because recognizing the cue is what keeps your entrances on time. You do not need other parts word-perfect, just reliable enough to set up your lines.",
      },
      {
        q: "What does cue-to-cue mean for an actor?",
        a: "For an actor, cue-to-cue rehearsal means practicing each of your lines as the answer to the cue that triggers it, rather than learning your lines in isolation. It mirrors how a scene actually runs, so the lines hold up when there is no time to think.",
      },
      {
        q: "How do I practice cues on my own?",
        a: "Cover your lines, take each cue, and deliver your line from memory, then check. Re-run anything you miss before moving on. A cue-based tool can hold the cues for you so you stay in the scene instead of managing the page.",
      },
      {
        q: "Why learn cues and not just my lines?",
        a: "You can know every word and still freeze if you do not recognize when to say it. Learning your cues prevents the long pauses that happen when you remember a line but not its trigger, and it keeps timing tight once you are back with other actors.",
      },
    ],
    body: `
<section class="quick-answer" data-rough data-rough-double data-rough-seed="2" aria-labelledby="quick-answer">
  <h2 id="quick-answer">Quick answer</h2>
  <p>Cue-to-cue rehearsal means practicing your lines as answers to the cues that trigger them. A cue is the line right before yours. By drilling the hand-off rather than your lines alone, you build the trigger-and-response a scene runs on, so your lines hold up under pressure.</p>
</section>

<section aria-labelledby="terms">
  <h2 id="terms">The words, defined</h2>
  <dl>
    <dt>Cue</dt>
    <dd>The line, usually another character's, that comes right before yours and signals your turn to speak.</dd>
    <dt>Cue line</dt>
    <dd>Another name for that trigger line; the words you listen for so you know your line is next.</dd>
    <dt>Cue-to-cue rehearsal</dt>
    <dd>Running your lines as responses to their cues, so each cue reliably triggers the right line.</dd>
    <dt>Off-book</dt>
    <dd>Able to perform without holding the script, recalling your lines from memory.</dd>
  </dl>
</section>

<section aria-labelledby="why">
  <h2 id="why">Why cues matter more than your lines alone</h2>
  <p>Knowing your words is only half the job. In performance, the cue is what tells you when to speak. Actors who learn lines in isolation often freeze waiting for a trigger they never practiced. Learning the cue together with the line removes that gap.</p>
</section>

<section aria-labelledby="solo">
  <h2 id="solo">How to rehearse cue-to-cue on your own</h2>
  <p>Cover your lines. Take the cue, deliver your line from memory, then reveal to check. Re-run any miss right away rather than waiting for the next pass. Keep the loop short and the script out of your hands as soon as you can.</p>
</section>

<section aria-labelledby="two-meanings">
  <h2 id="two-meanings">A note on two meanings</h2>
  <p>In technical rehearsal, a "cue-to-cue" is when a company skips between technical cues to set lights and sound. This page is about the actor's sense: drilling your lines against the cues that trigger them. Both work cue by cue, but the goals differ.</p>
</section>

<section aria-labelledby="where">
  <h2 id="where">Where Your Script helps</h2>
  <p>Your Script turns a scene into cue and line pairs, so you can run cue-to-cue on your own without recording the other parts. See the cue, answer it, and move on. For solo practice more broadly, see rehearsing without a scene partner.</p>
</section>
`,
  },
];

// Convenience: only the generated static pages.
export const GENERATED_PAGES = PAGES.filter((p) => p.generate);
